/**
 * SEO NEXUS - Real Google Search Console & Indexing API Feeder Engine
 */

const GoogleConsoleFeeder = (() => {
  // Generate Google Search Console Indexing API request payload
  function generateIndexingApiPayload(url, action = 'URL_UPDATED') {
    return {
      url: url,
      type: action,
      notifyTime: new Date().toISOString(),
      clientMetadata: {
        agent: 'SEONexus-GSC-Connector/2.4',
        apiVersion: 'v3',
        authType: 'OAuth2-ServiceAccount',
        scope: 'https://www.googleapis.com/auth/indexing'
      }
    };
  }

  // Real API Dispatcher to backend server
  async function publishToGoogleIndexingApi(url, action = 'URL_UPDATED', credentials = {}) {
    try {
      const token = typeof SEONexus !== 'undefined' && SEONexus.getAuthToken ? SEONexus.getAuthToken() : null;
      let saKey = credentials.serviceAccountKey;
      if (!saKey && credentials.email && credentials.token) {
        saKey = {
          client_email: credentials.email,
          private_key: credentials.token
        };
      }

      const res = await fetch('/api/gsc/publish', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          ...(token ? { 'Authorization': `Bearer ${token}` } : {})
        },
        body: JSON.stringify({
          url,
          type: action,
          serviceAccountKey: saKey,
          bearerToken: credentials.token && !/PRIVATE KEY/.test(credentials.token)
            ? credentials.token
            : undefined
        })
      });

      const data = await res.json();
      return {
        ...data,
        status: res.status
      };
    } catch (e) {
      console.error('Backend API publish error:', e);
      return {
        success: false,
        status: 500,
        error: e.message || 'Network communication error',
        url,
        type: action
      };
    }
  }

  // Generate Googlebot Meta Tags bundle with extracted keywords
  function generateMetaTags(state) {
    const keywordsStr = (state.extractedKeywords || [])
      .slice(0, 12)
      .map(k => k.term)
      .join(', ');

    return `<!-- ==============================================
     Googlebot & Google Search Console Verified Tags
     Target URL: ${state.targetUrl}
     Generated by SEO Nexus
============================================== -->
<title>${state.metaTitle}</title>
<meta name="description" content="${state.metaDescription}">
<meta name="keywords" content="${keywordsStr}">
<link rel="canonical" href="${state.auditDetails?.canonical || state.targetUrl}">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
<meta name="googlebot" content="index, follow, snippet, archive">
<meta name="google-site-verification" content="GSC_NEXUS_TOKEN_${Math.random().toString(36).substring(2, 12).toUpperCase()}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="${state.targetUrl}">
<meta property="og:title" content="${state.metaTitle}">
<meta property="og:description" content="${state.metaDescription}">
<meta property="og:image" content="${state.auditDetails?.ogTags?.image || state.targetUrl + '/og-banner.jpg'}">

<!-- Twitter Cards -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${state.metaTitle}">
<meta name="twitter:description" content="${state.metaDescription}">
<meta name="twitter:image" content="${state.auditDetails?.ogTags?.image || state.targetUrl + '/og-banner.jpg'}">`;
  }

  // Generate JSON-LD Structured Data enriched with keywords
  function generateJsonLdSchema(state) {
    const topKeywords = (state.extractedKeywords || []).slice(0, 8).map(k => k.term);

    const schemaObj = {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "WebSite",
          "@id": `${state.targetUrl}#website`,
          "url": state.targetUrl,
          "name": state.siteName,
          "description": state.metaDescription,
          "keywords": topKeywords.join(', '),
          "potentialAction": {
            "@type": "SearchAction",
            "target": `${state.targetUrl}/search?q={search_term_string}`,
            "query-input": "required name=search_term_string"
          },
          "inLanguage": "en-US"
        },
        {
          "@type": "Organization",
          "@id": `${state.targetUrl}#organization`,
          "name": state.siteName,
          "url": state.targetUrl,
          "logo": {
            "@type": "ImageObject",
            "url": `${state.targetUrl}/logo.png`,
            "caption": state.siteName
          },
          "knowsAbout": topKeywords
        },
        {
          "@type": "WebPage",
          "@id": `${state.targetUrl}#webpage`,
          "url": state.targetUrl,
          "name": state.metaTitle,
          "isPartOf": { "@id": `${state.targetUrl}#website` },
          "description": state.metaDescription,
          "about": topKeywords.map(kw => ({
            "@type": "Thing",
            "name": kw
          }))
        }
      ]
    };

    return `<script type="application/ld+json">\n${JSON.stringify(schemaObj, null, 2)}\n</script>`;
  }

  // Generate robots.txt file with Googlebot instructions
  function generateRobotsTxt(state) {
    const url = state.targetUrl.replace(/\/$/, '');
    return `# Robots.txt generated by SEO Nexus for Google Search Console
User-agent: Googlebot
Allow: /
Crawl-delay: 0

User-agent: Googlebot-Image
Allow: /images/
Allow: /assets/

User-agent: *
Allow: /
Disallow: /admin/
Disallow: /checkout/
Disallow: /api/private/

# Sitemap location for Google Search Console crawler
Sitemap: ${url}/sitemap.xml`;
  }

  // Generate sitemap.xml with target URL and keyword categories
  function generateSitemapXml(state) {
    const today = new Date().toISOString().split('T')[0];
    const url = state.targetUrl.replace(/\/$/, '');
    const keywords = (state.extractedKeywords || []).slice(0, 6);

    let items = `  <url>
    <loc>${url}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>\n`;

    keywords.forEach((kw, i) => {
      const slug = kw.term.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const prio = (0.8 - (i * 0.05)).toFixed(1);
      items += `  <url>
    <loc>${url}/category/${slug}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${prio}</priority>
  </url>\n`;
    });

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${items}</urlset>`;
  }

  // Real live technical inspection & Google Indexing dispatch (Zero fake delays)
  async function inspectAndPublishGoogle(targetUrl, keywords, onLogUpdate, onComplete) {
    const time = () => new Date().toLocaleTimeString();

    onLogUpdate({
      time: time(),
      tag: 'PROBE',
      text: `Connecting to live server and checking Googlebot crawlability for: <span class="text-highlight">${targetUrl}</span>`,
      type: 'log-info'
    });

    // Step 1: Real Technical Googlebot Crawlability Inspection
    let inspectData = null;
    try {
      const inspectResp = await fetch('/api/gsc/inspect', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: targetUrl })
      });
      inspectData = await inspectResp.json();
    } catch (e) {
      onLogUpdate({
        time: time(),
        tag: 'WARN',
        text: `Inspection probe error: ${e.message}`,
        type: 'log-tag'
      });
    }

    if (inspectData && inspectData.success) {
      onLogUpdate({
        time: time(),
        tag: 'HTTP_' + inspectData.httpStatus,
        text: `Target server reachable (HTTP ${inspectData.httpStatus} in ${inspectData.latency}). Checked with Googlebot/2.1 User-Agent.`,
        type: inspectData.httpStatus === 200 ? 'log-success' : 'log-tag'
      });

      const robotsAllowed = inspectData.robotsTxt?.allowed !== false;
      onLogUpdate({
        time: time(),
        tag: 'ROBOTS_TXT',
        text: inspectData.robotsTxt?.found
          ? (robotsAllowed ? 'robots.txt verified: Googlebot crawl is ALLOWED.' : '⚠️ robots.txt disallows Googlebot on this path!')
          : 'No robots.txt found (default: crawl allowed).',
        type: robotsAllowed ? 'log-success' : 'log-tag'
      });

      onLogUpdate({
        time: time(),
        tag: 'META_ROBOTS',
        text: `Robots directives: <code>${inspectData.metaRobots}</code> (X-Robots-Tag: ${inspectData.xRobotsTag})`,
        type: 'log-info'
      });

      if (inspectData.canonical) {
        onLogUpdate({
          time: time(),
          tag: 'CANONICAL',
          text: `Canonical declared: <code>${inspectData.canonical}</code>`,
          type: 'log-info'
        });
      }

      if (inspectData.sitemapDetected) {
        let origin = targetUrl;
        try { origin = new URL(targetUrl).origin; } catch (e) {}
        onLogUpdate({
          time: time(),
          tag: 'SITEMAP',
          text: `Detected XML sitemap at ${origin}/sitemap.xml`,
          type: 'log-success'
        });
      }
    }

    if (keywords && keywords.length > 0) {
      onLogUpdate({
        time: time(),
        tag: 'KEYWORDS',
        text: `Mapped ${keywords.length} structured keyword entities from attached file to payload.`,
        type: 'log-tag'
      });
    }

    // Step 2: Real Google Indexing API Dispatch
    onLogUpdate({
      time: time(),
      tag: 'DISPATCH',
      text: `Dispatching request to Google Indexing API (POST https://indexing.googleapis.com/v3/urlNotifications:publish)...`,
      type: 'log-info'
    });

    const creds = typeof SEONexus !== 'undefined' && SEONexus.getCredentials ? SEONexus.getCredentials() : {};
    const result = await publishToGoogleIndexingApi(targetUrl, 'URL_UPDATED', creds);

    if (result.success) {
      onLogUpdate({
        time: time(),
        tag: 'GSC_200',
        text: `Google Indexing API accepted notification (HTTP 200 OK). URL registered in Googlebot crawl queue.`,
        type: 'log-success'
      });
    } else if (result.requiresCredentials || result.status === 401) {
      onLogUpdate({
        time: time(),
        tag: 'AUTH_REQUIRED',
        text: `⚠️ ${result.error || 'Google Service Account credentials required. Configure in API Credentials Setup.'}`,
        type: 'log-tag'
      });
    } else {
      onLogUpdate({
        time: time(),
        tag: 'GSC_' + (result.status || 'ERR'),
        text: `Google API response (HTTP ${result.status}): ${result.error || (result.googleResponse && result.googleResponse.error && result.googleResponse.error.message) || 'Request rejected.'}`,
        type: 'log-tag'
      });
    }

    if (result.gscDeepLink) {
      onLogUpdate({
        time: time(),
        tag: 'GSC_PORTAL',
        text: `🔗 Official GSC Inspection: <a href="${result.gscDeepLink}" target="_blank" rel="noopener" style="color: var(--accent-cyan); text-decoration: underline; font-weight: 600;">Click to Open URL in Google Search Console & Request Indexing</a>`,
        type: 'log-info'
      });
    }

    if (onComplete) {
      onComplete({ ...result, inspectData });
    }
  }

  return {
    generateIndexingApiPayload,
    publishToGoogleIndexingApi,
    generateMetaTags,
    generateJsonLdSchema,
    generateRobotsTxt,
    generateSitemapXml,
    inspectAndPublishGoogle
  };
})();
